### ISSUE TITLE
panic on refresh: index out of range

### ISSUE THREAD

**Issue by kerneis-anssi** [thediveo/lxkns#21]
I followed the "Getting started" using `make deploy` with Docker. I get to the web interface, but when I hit "refresh", nothing happens in the UI and I see the following in the logs:

```
[…]
lxkns_1  | INFO[2022-06-30T08:57:00Z] found 18 net namespaces joined by processes  
lxkns_1  | DEBU[2022-06-30T08:57:00Z] discovering time namespaces used by processes... 
lxkns_1  | DEBU[2022-06-30T08:57:00Z] found namespace time:[4026531834] at /proc/1095/ns/time[=rtkit-daemon] 
lxkns_1  | INFO[2022-06-30T08:57:00Z] found 1 time namespace joined by processes   
lxkns_1  | DEBU[2022-06-30T08:57:00Z] discovering fd-referenced namespaces...      
lxkns_1  | 2022/06/30 08:57:00 http: panic serving 172.18.0.1:38946: runtime error: index out of range [8] with length 8
lxkns_1  | goroutine 62 [running]:
lxkns_1  | net/http.(*conn).serve.func1()
lxkns_1  | 	/usr/local/go/src/net/http/server.go:1801 +0xb9
lxkns_1  | panic({0x110a960, 0xc0003cb548})
lxkns_1  | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
lxkns_1  | github.com/thediveo/lxkns/species.IDwithType({0xc00012b9b0, 0xc00012b230})
lxkns_1  | 	/src/species/id.go:84 +0x1a7
lxkns_1  | github.com/thediveo/lxkns/discover.scanFd(0xc000000005, {0x116b8d9, 0x5}, 0x0, 0xc0005302c0)
lxkns_1  | 	/src/discover/discovery_fd.go:86 +0x3b3
lxkns_1  | github.com/thediveo/lxkns/discover.discoverFromFd(0x80, {0x116b8d9, 0x5}, 0xc0005302c0)
lxkns_1  | 	/src/discover/discovery_fd.go:49 +0x70
lxkns_1  | github.com/thediveo/lxkns/discover.Namespaces({0xc00063f858, 0x3, 0x18})
lxkns_1  | 	/src/discover/discovery.go:167 +0x3a3
lxkns_1  | main.GetNamespacesHandler.func1({0x129deb8, 0xc0001510a0}, 0x2)
lxkns_1  | 	/src/cmd/lxkns/endpoints.go:33 +0xe5
lxkns_1  | net/http.HandlerFunc.ServeHTTP(0xc000000004, {0x129deb8, 0xc0001510a0}, 0xc000702940)
lxkns_1  | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
lxkns_1  | main.requestLogger.func1({0x129deb8, 0xc0001510a0}, 0xc0004d8600)
lxkns_1  | 	/src/cmd/lxkns/server.go:41 +0xed
lxkns_1  | net/http.HandlerFunc.ServeHTTP(0xc0004d8400, {0x129deb8, 0xc0001510a0}, 0xc0007029f8)
lxkns_1  | 	/usr/local/go/src/net/http/server.go:2046 +0x2f
lxkns_1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f2240, {0x129deb8, 0xc0001510a0}, 0xc0004d8000)
lxkns_1  | 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
lxkns_1  | net/http.serverHandler.ServeHTTP({0xc000716060}, {0x129deb8, 0xc0001510a0}, 0xc0004d8000)
lxkns_1  | 	/usr/local/go/src/net/http/server.go:2878 +0x43b
lxkns_1  | net/http.(*conn).serve(0xc00062a460, {0x12a83a8, 0xc0001c10b0})
lxkns_1  | 	/usr/local/go/src/net/http/server.go:1929 +0xb08
lxkns_1  | created by net/http.(*Server).Serve
lxkns_1  | 	/usr/local/go/src/net/http/server.go:3033 +0x4e8
```

**Comment by kerneis-anssi** [comment]
Thanks, that fixed it!
